version: "3.8"

services:
  php:
    build:
      context: ./php-app
      dockerfile: Dockerfile
    container_name: symfony-app
    volumes:
      - ./php-app:/var/www/html
    expose:
      - "80"

  node:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    container_name: express-app
    volumes:
      - ./node-app:/usr/src/app
    command: ["npm", "start"]
    expose:
      - "3000"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: fastapi-app
    volumes:
      - ./python-app:/usr/src/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - node
      - python
