services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ./static:/srv/static
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config/.htpasswd:/etc/nginx/.htpasswd
